version: '3.7'

services:

  user-service:
    image: user-service:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
    networks:
      - exam-system-network
    depends_on:
      - eureka-naming-service
      - db
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-naming-service:8761/eureka
      MYSQL_HOST: localhost
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123456
      MYSQL_PORT: 3306

      #spring.datasource.url: jdbc:mysql://db:3307/Online_Exam_System?createDatabaseIfNotExist=true

  exam-service:
    image: exam-service:0.0.1-SNAPSHOT
    ports:
      - "9002:9002"
    networks:
      - exam-system-network
    depends_on:
      - eureka-naming-service
      - db
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-naming-service:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/Exam?createDatabaseIfNotExist=true

  api-gateway:
    image: api-gateway:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    networks:
      - exam-system-network
    depends_on:
      - eureka-naming-service
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-naming-service:8761/eureka

  user-interface:
    image: user-interface:0.0.1-SNAPSHOT
    ports:
      - "8085:8085"
    networks:
      - exam-system-network
    depends_on:
      - eureka-naming-service
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-naming-service:8761/eureka
  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: Online_Exam_System
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE_USER: root
      MYSQL_DATABASE_PASSWORD: 123456
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/Online_Exam_System?createDatabaseIfNotExist=true
    ports:
      - "3307:3306"
    networks:
      - exam-system-network
    volumes:
      - db_data:/var/lib/mysql:rw
  #  db-exam:
#    image: mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: 123456
#      MYSQL_DATABASE: Exam
##      MYSQL_USER: db
##      MYSQL_PASSWORD: 1234
#    ports:
#      - "3308:3306"
#    volumes:
#      - db_data:/var/lib/mysql:rw
#    networks:
#      - exam-system-network

  eureka-naming-service:
    image: eureka-server:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    networks:
      - exam-system-network

volumes:
  db_data: { }

networks:
  exam-system-network: